---
title: Pretty Bird Chicken
timezone: UTC
collections:
  drinks:
    title: Drinks
    output: true
  menu:
    title: Menu
    output: true
  posts:
    title: Posts
    output: true
  team:
    title: Team
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    read_time: true
lang: en-US
email: 
description: |-
  No reservations. First come, first serve. Please direct all other inquiries to info@prettybirdchicken.com

  call: (310)487-8413
baseurl: 
url: 
author:
  name: 
  twitter: 
  picture: 
twitter_username: 
github_username: 
logo: 
markdown: kramdown
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-paginate
feed:
  path: atom.xml
paginate: 10
paginate_path: "/page:num/"
exclude:
- ".asset-cache"
- ".bundle"
- ".codeclimate.yml"
- ".editorconfig"
- ".gitattributes"
- ".jekyll-assets-cache"
- ".sass-cache"
- ".scss-lint.yml"
- CHANGELOG
- Gemfile
- Gemfile.lock
- LICENSE
- node_modules
- Rakefile
- README
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- "/docs"
- "/example"
address: 1234 Main Street Salt Lake City, UT 123456
subtext: nashville style hot chicken
phone: "(347) 555-1234"
hours: |-
  M-Th 5p–11p
  F-Sa 12p–11p
  Su 10a–11p
asset: "/uploads/20987348_127394674557791_1525660584987590656_n.jpg"
